export const banner = [
  {
    banner: 0,
    source: "images/advert/lg.jpg",
    href: "#",
  },
  {
    banner: 1,
    source: "images/advert/samsung.jpg",
    href: "#",
  },
  {
    banner: 2,
    source: "images/advert/macbook.jpg",
    href: "#",
  },
  {
    banner: 3,
    source: "images/advert/lgdays.png",
    href: "#",
  },
  {
    banner: 4,
    source: "images/advert/iphone12.jpg",
    href: "#",
  },
  {
    banner: 5,
    source: "images/advert/xiaomi.jpg",
    href: "#",
  },
];

export const bannerFullSize = [
  {
    banner: 0,
    source: "images/advert/fullscreen/testImage.jpg",
    href: "#",
  },
  {
    banner: 1,
    source: "images/advert/fullscreen/e74667f609f9fc4dcd9c29065cc4e2f1.jpg",
    href: "#",
  },
  {
    banner: 2,
    source: "images/advert/fullscreen/2.jpg",
    href: "#",
  },
  {
    banner: 3,
    source: "images/advert/fullscreen/3.jpg",
    href: "#",
  },
  {
    banner: 4,
    source: "images/advert/fullscreen/4.jpg",
    href: "#",
  },
];

export const thumb = [
  {
    thumb: 0,
    category: "Tablets",
    source: "images/thumb/ipads.jpg",
    href: "#",
  },
  {
    thumb: 1,
    category: "Laptops",
    source: "images/thumb/laptops.jpg",
    href: "#",
  },
  {
    thumb: 3,
    category: "Consoles",
    source: "images/thumb/consoles.jpg",
    href: "#",
  },
  {
    thumb: 4,
    category: "TV",
    source: "images/thumb/tv.jpg",
    href: "#",
  },
  {
    thumb: 5,
    category: "Headphones",
    source: "images/thumb/headphones.jpg",
    href: "#",
  },
  {
    thumb: 6,
    category: "Fridges",
    source: "images/thumb/fridges.jpg",
    href: "#",
  },
  {
    thumb: 7,
    category: "Smartphones",
    source: "images/thumb/phones.jpg",
    href: "#",
  },
  {
    thumb: 8,
    category: "Speakers",
    source: "images/thumb/audio.jpg",
    href: "#",
  },
];

export const productsPopular = [
  {
    prod: 0,
    brand: "LG",
    model: "32LM6300PLA TV",
    category: "tv",
    price: 259.99,
    source: "images/products/popular/lg tv.jpg",
    href: "products.html",
    id: "popular",
    qty: 10,
  },
  {
    prod: 1,
    brand: "Lenovo",
    model: "IdeaTab M10 X505",
    category: "tablets",
    price: 135.99,
    source: "images/products/popular/lenovo.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 2,
    brand: "Xiaomi",
    model: "Redmi 9 64Gb Sun",
    category: "smartphones",
    price: 149.0,
    source: "images/products/popular/xiaomi.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 3,
    brand: "Beko",
    model: "CSA240K30SN",
    category: "fridges",
    price: 228.99,
    source: "images/products/popular/beko.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 4,
    brand: "Acer",
    model: "A315-23 15.6 FHD R3",
    category: "laptops",
    price: 549.99,
    source: "images/products/popular/acer.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 5,
    brand: "Indesit",
    model: "LR7 S1",
    category: "fridges",
    price: 254.99,
    source: "images/products/popular/indesit.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 6,
    brand: "Apple",
    model: "iPods Pro",
    category: "earphones",
    price: 250.0,
    source: "images/products/popular/ipods.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 7,
    brand: "PlayStation",
    model: "PS4 Pro 1Tb",
    category: "consoles",
    price: 340.0,
    source: "images/products/popular/ps4.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 8,
    brand: "Apple",
    model: "iPhone 11",
    category: "smartphones",
    price: 750.0,
    source: "images/products/popular/iphone11.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 9,
    brand: "Samsung",
    model: "Galaxy A10 64Gb",
    category: "smartphones",
    price: 499.99,
    source: "images/products/popular/samsung.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
];

export const productsNew = [
  {
    prod: 10,
    brand: "Samsung",
    model: "40APLN4TU Smart TV",
    category: "tv",
    price: 599.99,
    source: "images/products/new/samsung.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 11,
    brand: "LG",
    model: "4LM6300PLA ",
    category: "fridges",
    price: 359.99,
    source: "images/products/new/lgfridge.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 12,
    brand: "Lenovo",
    model: "lenovoPAd 128Gb ",
    category: "tablets",
    price: 289.0,
    source: "images/products/new/lenovopad.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 13,
    brand: "Microsoft",
    model: "XBOX series S ",
    category: "consoles",
    price: 250.0,
    source: "images/products/new/xboxs.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 14,
    brand: "Nintendo",
    model: "Nintendo Switch ",
    category: "consoles",
    price: 249.99,
    source: "images/products/new/nintendo.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 15,
    brand: "Samsung",
    model: "42UHDTV ",
    category: "tv",
    price: 689.99,
    source: "images/products/new/samsunguhd.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
];

export const goodsArr = [
  {
    prod: 0,
    brand: "LG",
    model: "32LM6300PLA TV",
    category: "tv",
    price: 259.99,
    source: "images/products/popular/lg tv.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 1,
    brand: "Lenovo",
    model: "IdeaTab M10 X505",
    category: "tablets",
    price: 135.99,
    source: "images/products/popular/lenovo.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 2,
    brand: "Xiaomi",
    model: "Redmi 9 64Gb Sun",
    category: "smartphones",
    price: 149.0,
    source: "images/products/popular/xiaomi.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 3,
    brand: "Beko",
    model: "CSA240K30SN",
    category: "fridges",
    price: 228.99,
    source: "images/products/popular/beko.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 4,
    brand: "Acer",
    model: "A315-23 15.6 FHD R3",
    category: "laptops",
    price: 549.99,
    source: "images/products/popular/acer.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 5,
    brand: "Indesit",
    model: "LR7 S1",
    category: "fridges",
    price: 254.99,
    source: "images/products/popular/indesit.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 6,
    brand: "Apple",
    model: "iPods Pro",
    category: "earphones",
    price: 250.0,
    source: "images/products/popular/ipods.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 7,
    brand: "PlayStation",
    model: "PS4 Pro 1Tb",
    category: "consoles",
    price: 340.0,
    source: "images/products/popular/ps4.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 8,
    brand: "Apple",
    model: "iPhone 11",
    category: "smartphones",
    price: 750.0,
    source: "images/products/popular/iphone11.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 9,
    brand: "Samsung",
    model: "Galaxy A10 64Gb",
    category: "smartphones",
    price: 499.99,
    source: "images/products/popular/samsung.jpg",
    href: "#",
    id: "popular",
    qty: 10,
  },
  {
    prod: 10,
    brand: "Samsung",
    model: "40APLN4TU Smart TV",
    category: "tv",
    price: 599.99,
    source: "images/products/new/samsung.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 11,
    brand: "LG",
    model: "4LM6300PLA ",
    category: "fridges",
    price: 359.99,
    source: "images/products/new/lgfridge.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 12,
    brand: "Lenovo",
    model: "lenovoPAd 128Gb ",
    category: "tablets",
    price: 289.0,
    source: "images/products/new/lenovopad.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 13,
    brand: "Microsoft",
    model: "XBOX series S ",
    category: "consoles",
    price: 250.0,
    source: "images/products/new/xboxs.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 14,
    brand: "Nintendo",
    model: "Nintendo Switch ",
    category: "consoles",
    price: 249.99,
    source: "images/products/new/nintendo.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
  {
    prod: 15,
    brand: "Samsung",
    model: "42UHDTV ",
    category: "tv",
    price: 689.99,
    source: "images/products/new/samsunguhd.jpg",
    href: "#",
    id: "new",
    qty: 10,
  },
];
